export default {
	songs: [
		{
			id: 0,
			name: 'Natural',
			author: 'Imagine Dragons',
			path: './resources/music/Imagine Dragons  Natural.mp3',
			thumbnail: './resources/images/natural.png',
		},
		{
			id: 1,
			name: 'Never gonna give you up',
			author: 'Rick Astley',
			path: './resources/music/Rick Astley  Never Gonna Give You Up.mp3',
			thumbnail: './resources/images/rick.png',
		},
		{
			id: 2,
			name: 'A Cruel Angels Thesis',
			author: 'Yoko Takahashi, from Evangelion',
			path: './resources/music/A Cruel Angels Thesis Yoko Takahashi.mp3',
			thumbnail: './resources/images/Evangelion.png',
		},
		{
			id: 3,
			name: 'Stay with me',
			author: 'Miki Matsubara',
			path: './resources/music/Miki Matsubara  Stay With Me.mp3',
			thumbnail: './resources/images/staywithme.png',
		},
		{
			id: 4,
			name: 'Sanctuary',
			author: 'Joji',
			path: './resources/music/Sanctuary Joji.mp3',
			thumbnail: './resources/images/joji.png',
		},
		{
			id: 5,
			name: 'Warriors Ft. Imagine Dragons',
			author: 'League of Legends and Imagine Dragons',
			path: './resources/music/Warriors ft Imagine Dragons.mp3',
			thumbnail: './resources/images/warriors.png',
		},
		{
			id: 6,
			name: 'Hikaru nara',
			author: 'Goose House',
			path: './resources/music/Hikaru nara by Goose House.mp3',
			thumbnail: './resources/images/hikarunara.png',
		},
		{
			id: 7,
			name: 'Jealousy jealousy',
			author: 'Olivia Rodrigo',
			path: './resources/music/Olivia Rodrigo  jealousy jealousy.mp3',
			thumbnail: './resources/images/sour.png',
		},
		{
			id: 8,
			name: 'Yoru ni kakeru',
			author: 'YOASOBI',
			path: './resources/music/Yoru ni kakeru - YOASOBI.mp3',
			thumbnail: './resources/images/yoasobi.png',
		},
		{
			id: 9,
			name: 'Moves like Jagger Ft. Christina Aguilera',
			author: 'Maroon 5 and Christina Aguilera',
			path: './resources/music/Moves Like Jagger  Maroon 5 Feat Christina Aguilera.mp3',
			thumbnail: './resources/images/jagger.png',
		},
		{
			id: 10,
			name: 'Blessed by the Storm, The Stormlight Archive',
			author: 'THERAGON',
			path: './resources/music/THERAGON  Blessed by the Storm fanmade The Stormlight Archive.mp3',
			thumbnail: './resources/images/theragon.png',
		},
		{
			id: 11,
			name: 'Godzilla Ft. Juice',
			author: 'Eminem and Juice',
			path: './resources/music/Eminem Godzilla ft Juice.mp3',
			thumbnail: './resources/images/eminem.png',
		},
		{
			id: 12,
			name: 'Ew',
			author: 'Joji',
			path: './resources/music/Ew Joji.mp3',
			thumbnail: './resources/images/joji.png',
		},
	],
};
